version: '3.8'

services:
  react-app-3001:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    command: ["serve", "-s", "build", "-l", "3001"]
